# Generated by Django 2.2.5 on 2019-09-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='followers',
        ),
        migrations.AddField(
            model_name='artist',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_related', to='home.Artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
